apiVersion: v1
kind: Service
metadata:
  name: nis2compass-service
  namespace: opensecstack
  labels:
    app: nis2compass
    app.kubernetes.io/part-of: opensecstack
spec:
  type: ClusterIP
  selector:
    app: nis2compass
  ports:
    - name: http
      port: 8090
      targetPort: 8090
      protocol: TCP
