package meetings

import (
	"context"
	"errors"
	"fmt"
	"net/url"
	"time"
)

// ErrNotImplemented is returned by stub functions that require external
// SDK keys or backend provisioning before they can be completed.
var ErrNotImplemented = errors.New("not implemented")

// Token holds the OAuth2 credentials returned after a successful
// authorization-code exchange with a meeting platform.
type Token struct {
	AccessToken  string
	RefreshToken string
	ExpiresAt    time.Time
	Platform     MeetingPlatform
}

// authorizeBase holds the platform-specific OAuth2 authorize endpoint.
var authorizeBase = map[MeetingPlatform]string{
	PlatformZoom:  "https://zoom.us/oauth/authorize",
	PlatformTeams: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
	PlatformWebEx: "https://webexapis.com/v1/authorize",
}

// teamsScopes is the space-separated scope list for the Teams (Azure AD)
// authorize request. The offline_access scope is required to receive a
// refresh token; OnlineMeetings.ReadWrite covers join/leave events.
const teamsScopes = "offline_access OnlineMeetings.ReadWrite"

// AuthorizeURL builds the platform-specific OAuth2 authorization URL
// that the operator's browser is redirected to at the start of the
// authorization-code flow.
//
// state is an opaque nonce generated by the caller (see handler) and
// must be validated in the callback to prevent CSRF.
// redirectURI must match the URI registered in the platform developer
// portal exactly (case-sensitive, including trailing slash).
func AuthorizeURL(platform MeetingPlatform, clientID, state, redirectURI string) (string, error) {
	base, ok := authorizeBase[platform]
	if !ok {
		return "", fmt.Errorf("unknown platform %q", platform)
	}

	q := url.Values{}
	q.Set("client_id", clientID)
	q.Set("redirect_uri", redirectURI)
	q.Set("response_type", "code")
	q.Set("state", state)

	// Teams requires an explicit scope list; Zoom and WebEx derive the
	// granted scopes from the app configuration in the developer portal.
	if platform == PlatformTeams {
		q.Set("scope", teamsScopes)
	}

	return base + "?" + q.Encode(), nil
}

// ExchangeCode exchanges an authorization code for an access token.
//
// Phase 4.3: implement token exchange once SDK keys are provisioned.
// Each platform has a different token endpoint and POST body format:
//   - Zoom:  POST https://zoom.us/oauth/token with Basic auth (client_id:client_secret)
//   - Teams: POST https://login.microsoftonline.com/common/oauth2/v2.0/token
//   - WebEx: POST https://webexapis.com/v1/access_token
//
// Store the returned Token (access + refresh) in the operator's secret
// manager; the refresh token must be used before ExpiresAt to maintain
// continuous access.
func ExchangeCode(_ context.Context, _ MeetingPlatform, _ string, _ string) (*Token, error) {
	// Phase 4.3: implement token exchange once SDK keys are provisioned.
	return nil, ErrNotImplemented
}
