version: "2"
run:
  go: "1.24"
linters:
  enable:
    - bodyclose
    - gosec
    - misspell
    - revive
  disable:
    - govet
  settings:
    misspell:
      locale: UK
      ignore-rules:
        - cancelled
        - catalogue
        - summarise
        - materialise
        - recognised
    revive:
      rules:
        - name: exported
          severity: warning
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
    paths:
      - rust
      - python
      - web
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - rust
      - python
      - web
      - third_party$
      - builtin$
      - examples$
