FROM node:20-alpine
WORKDIR /app
RUN chown node:node /app
COPY --chown=node:node package*.json ./
RUN npm config set fetch-retries 5 && npm config set fetch-retry-maxtimeout 120000 && npm config set fetch-timeout 600000 && npm install
COPY --chown=node:node . .
EXPOSE 3000
CMD ["npm", "run", "dev"]
