package reporter

import (
	"bytes"
	"fmt"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/opensecstack/apiguard/internal/domain"
	"github.com/opensecstack/apiguard/internal/version"
)

// PDFReporter generates a well-formatted, human-readable security report
// served as text/plain with a .txt filename.  The format is designed to be
// easily readable in any text viewer and is structurally equivalent to a
// printed report.
//
// To upgrade to true binary PDF output in the future, replace the Generate
// body with a call to a library such as github.com/go-pdf/fpdf while keeping
// this file's public interface identical, and update reportContentType in
// scans.go to return "application/pdf".
type PDFReporter struct{}

const (
	pdfLineWidth   = 80
	pdfSectionLine = "=" // repeated to pdfLineWidth
	pdfDividerLine = "-" // repeated to pdfLineWidth
)

// Generate produces the formatted report bytes.
func (r *PDFReporter) Generate(result *domain.ScanResult) ([]byte, error) {
	var b bytes.Buffer

	duration := result.CompletedAt.Sub(result.StartedAt)
	generatedAt := time.Now().UTC().Format(time.RFC3339)

	writeLine := func(s string) { b.WriteString(s); b.WriteByte('\n') }
	writeSep := func(ch string) { writeLine(strings.Repeat(ch, pdfLineWidth)) }
	writeBlank := func() { b.WriteByte('\n') }

	// ── Title block ──────────────────────────────────────────────────────────
	writeSep(pdfSectionLine)
	writeLine(center("APIGuard Security Report", pdfLineWidth))
	writeLine(center("Generated by APIGuard "+version.Version, pdfLineWidth))
	writeLine(center(generatedAt, pdfLineWidth))
	writeSep(pdfSectionLine)
	writeBlank()

	// ── Scan information ─────────────────────────────────────────────────────
	writeLine("SCAN INFORMATION")
	writeSep(pdfDividerLine)
	writeLine(fmt.Sprintf("  Scan ID    : %s", result.ID))
	writeLine(fmt.Sprintf("  Target URL : %s", result.Target))
	writeLine(fmt.Sprintf("  Status     : %s", strings.ToUpper(string(result.Status))))
	if !result.StartedAt.IsZero() {
		writeLine(fmt.Sprintf("  Started At : %s", result.StartedAt.Format(time.RFC3339)))
	}
	if !result.CompletedAt.IsZero() {
		writeLine(fmt.Sprintf("  Completed  : %s", result.CompletedAt.Format(time.RFC3339)))
	}
	if duration > 0 {
		writeLine(fmt.Sprintf("  Duration   : %s", duration))
	}
	if result.SpecHash != "" {
		writeLine(fmt.Sprintf("  Spec Hash  : %s", result.SpecHash))
	}
	writeBlank()

	// ── Summary ──────────────────────────────────────────────────────────────
	writeLine("FINDINGS SUMMARY")
	writeSep(pdfDividerLine)
	writeLine(fmt.Sprintf("  %-12s %5d", "Total", result.Summary.TotalFindings))
	writeLine(fmt.Sprintf("  %-12s %5d", "Critical", result.Summary.Critical))
	writeLine(fmt.Sprintf("  %-12s %5d", "High", result.Summary.High))
	writeLine(fmt.Sprintf("  %-12s %5d", "Medium", result.Summary.Medium))
	writeLine(fmt.Sprintf("  %-12s %5d", "Low", result.Summary.Low))
	writeLine(fmt.Sprintf("  %-12s %5d", "Info", result.Summary.Info))
	writeBlank()

	// ── Findings overview table ───────────────────────────────────────────────
	if len(result.Findings) > 0 {
		writeLine("FINDINGS OVERVIEW")
		writeSep(pdfDividerLine)
		writeLine(fmt.Sprintf("  %-10s  %-14s  %-36s  %s",
			"SEVERITY", "OWASP ID", "TITLE", "ENDPOINT"))
		writeLine(fmt.Sprintf("  %s  %s  %s  %s",
			strings.Repeat("-", 10), strings.Repeat("-", 14),
			strings.Repeat("-", 36), strings.Repeat("-", 16)))
		for _, f := range result.Findings {
			endpoint := f.EndpointMethod + " " + f.EndpointPath
			writeLine(fmt.Sprintf("  %-10s  %-14s  %-36s  %s",
				strings.ToUpper(string(f.Severity)),
				truncate(f.OWASPId, 14),
				truncate(f.Title, 36),
				truncate(endpoint, 40),
			))
		}
		writeBlank()

		// ── Detailed findings ─────────────────────────────────────────────────
		writeLine("DETAILED FINDINGS")
		writeSep(pdfSectionLine)
		writeBlank()

		for i, f := range result.Findings {
			writeLine(fmt.Sprintf("Finding %d of %d", i+1, len(result.Findings)))
			writeSep(pdfDividerLine)
			writeLine(fmt.Sprintf("  Title        : %s", f.Title))
			writeLine(fmt.Sprintf("  Severity     : %s", strings.ToUpper(string(f.Severity))))
			writeLine(fmt.Sprintf("  OWASP ID     : %s", f.OWASPId))
			writeLine(fmt.Sprintf("  Module       : %s", f.ModuleID))
			writeLine(fmt.Sprintf("  Endpoint     : %s %s", f.EndpointMethod, f.EndpointPath))
			if f.CVSSScore > 0 {
				writeLine(fmt.Sprintf("  CVSS Score   : %.1f", f.CVSSScore))
			}
			if f.CVSSVector != "" {
				writeLine(fmt.Sprintf("  CVSS Vector  : %s", f.CVSSVector))
			}
			writeLine(fmt.Sprintf("  Status       : %s", f.Status))
			writeLine(fmt.Sprintf("  Finding ID   : %s", f.ID))
			writeBlank()

			if f.Description != "" {
				writeLine("  Description:")
				writeWrapped(&b, f.Description, 4, pdfLineWidth)
				writeBlank()
			}

			if f.Evidence.Request != "" {
				writeLine("  Evidence - Request:")
				writeWrapped(&b, f.Evidence.Request, 4, pdfLineWidth)
				writeBlank()
			}

			if f.Evidence.Response != "" {
				writeLine("  Evidence - Response:")
				writeWrapped(&b, f.Evidence.Response, 4, pdfLineWidth)
				writeBlank()
			}

			if f.Remediation != "" {
				writeLine("  Remediation:")
				writeWrapped(&b, f.Remediation, 4, pdfLineWidth)
				writeBlank()
			}

			writeSep(pdfDividerLine)
			writeBlank()
		}
	} else {
		writeLine("No findings were detected during this scan.")
		writeBlank()
	}

	// ── Footer ────────────────────────────────────────────────────────────────
	writeSep(pdfSectionLine)
	writeLine(center("End of APIGuard Security Report", pdfLineWidth))
	writeLine(center("APIGuard "+version.Version+" — "+generatedAt, pdfLineWidth))
	writeSep(pdfSectionLine)

	return b.Bytes(), nil
}

// center returns s padded with spaces so that it is horizontally centred within
// a field of the given width.
func center(s string, width int) string {
	l := utf8.RuneCountInString(s)
	if l >= width {
		return s
	}
	pad := (width - l) / 2
	return strings.Repeat(" ", pad) + s
}

// truncate shortens s to at most n runes, appending "…" if truncated.
func truncate(s string, n int) string {
	if utf8.RuneCountInString(s) <= n {
		return s
	}
	runes := []rune(s)
	if n > 1 {
		return string(runes[:n-1]) + "…"
	}
	return string(runes[:n])
}

// writeWrapped writes text to b with the given left-margin indent, wrapping at
// maxWidth columns.
func writeWrapped(b *bytes.Buffer, text string, indent, maxWidth int) {
	prefix := strings.Repeat(" ", indent)
	available := maxWidth - indent
	if available < 20 {
		available = 20
	}

	// Preserve existing newlines; wrap each paragraph independently.
	paragraphs := strings.Split(text, "\n")
	for _, para := range paragraphs {
		if para == "" {
			b.WriteByte('\n')
			continue
		}
		words := strings.Fields(para)
		if len(words) == 0 {
			b.WriteByte('\n')
			continue
		}
		line := prefix
		lineLen := indent
		for _, word := range words {
			wl := utf8.RuneCountInString(word)
			if lineLen > indent && lineLen+1+wl > available+indent {
				b.WriteString(line)
				b.WriteByte('\n')
				line = prefix + word
				lineLen = indent + wl
			} else if lineLen == indent {
				line += word
				lineLen += wl
			} else {
				line += " " + word
				lineLen += 1 + wl
			}
		}
		if lineLen > indent {
			b.WriteString(line)
			b.WriteByte('\n')
		}
	}
}
