apiVersion: v1
kind: Service
metadata:
  name: {{ include "opensecstack.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: redis
    {{- include "opensecstack.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
