// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go         hand-written equivalent
// 	protoc                v3 (vertguard.ml.v1)
// source: proto/ml/v1/inference.proto
//
// WHY hand-written: protoc was not available on the build host that
// scaffolded Phase 4.2. The wire format (proto3 tag/length-prefixed
// fields) is implemented directly via google.golang.org/protobuf's
// `protowire` primitives, and a custom gRPC codec ("vertguard-mlpb")
// shuttles these messages on the network. Regenerate via the
// `proto-gen` Makefile target whenever the .proto changes — the
// regenerated file MUST keep the same field numbers and message
// names so existing servers stay compatible.

package mlpb

import (
	"fmt"
	"math"

	"google.golang.org/protobuf/encoding/protowire"
)

// math_Float* aliases keep the helper signatures self-documenting at the
// call site (vs. raw math.* in dense wire-format code).
func math_Float64bits(f float64) uint64    { return math.Float64bits(f) }
func math_Float64frombits(b uint64) float64 { return math.Float64frombits(b) }
func math_Float32bits(f float32) uint32    { return math.Float32bits(f) }
func math_Float32frombits(b uint32) float32 { return math.Float32frombits(b) }

// PromptScoreRequest is the single-input scoring shape for prompts.
type PromptScoreRequest struct {
	Input         string
	Context       string
	CorrelationId string
	Tenant        string
}

// Reset zeros the message — required by the gRPC codec.
func (m *PromptScoreRequest) Reset() { *m = PromptScoreRequest{} }

// String returns a debug-friendly form. Avoid leaking input bytes —
// only structural shape is interesting at log time.
func (m *PromptScoreRequest) String() string {
	return fmt.Sprintf("PromptScoreRequest{ctx=%q, corr=%q, tenant=%q, input_len=%d}",
		m.Context, m.CorrelationId, m.Tenant, len(m.Input))
}

// ProtoMessage marks this as a proto message (no-op tag).
func (*PromptScoreRequest) ProtoMessage() {}

// MarshalVT serialises the message to proto3 wire format.
func (m *PromptScoreRequest) MarshalVT() ([]byte, error) {
	var b []byte
	b = appendString(b, 1, m.Input)
	b = appendString(b, 2, m.Context)
	b = appendString(b, 3, m.CorrelationId)
	b = appendString(b, 4, m.Tenant)
	return b, nil
}

// UnmarshalVT parses proto3 wire bytes into the message.
func (m *PromptScoreRequest) UnmarshalVT(data []byte) error {
	for len(data) > 0 {
		num, typ, n := protowire.ConsumeTag(data)
		if err := protowire.ParseError(n); err != nil {
			return err
		}
		data = data[n:]
		switch num {
		case 1:
			s, n := consumeString(data, typ)
			m.Input = s
			data = data[n:]
		case 2:
			s, n := consumeString(data, typ)
			m.Context = s
			data = data[n:]
		case 3:
			s, n := consumeString(data, typ)
			m.CorrelationId = s
			data = data[n:]
		case 4:
			s, n := consumeString(data, typ)
			m.Tenant = s
			data = data[n:]
		default:
			n := protowire.ConsumeFieldValue(num, typ, data)
			if err := protowire.ParseError(n); err != nil {
				return err
			}
			data = data[n:]
		}
	}
	return nil
}

// PhishingScoreRequest mirrors PromptScoreRequest with a kind hint.
type PhishingScoreRequest struct {
	Input         string
	Kind          string
	CorrelationId string
	Tenant        string
}

func (m *PhishingScoreRequest) Reset() { *m = PhishingScoreRequest{} }
func (m *PhishingScoreRequest) String() string {
	return fmt.Sprintf("PhishingScoreRequest{kind=%q, corr=%q, tenant=%q, input_len=%d}",
		m.Kind, m.CorrelationId, m.Tenant, len(m.Input))
}
func (*PhishingScoreRequest) ProtoMessage() {}

func (m *PhishingScoreRequest) MarshalVT() ([]byte, error) {
	var b []byte
	b = appendString(b, 1, m.Input)
	b = appendString(b, 2, m.Kind)
	b = appendString(b, 3, m.CorrelationId)
	b = appendString(b, 4, m.Tenant)
	return b, nil
}

func (m *PhishingScoreRequest) UnmarshalVT(data []byte) error {
	for len(data) > 0 {
		num, typ, n := protowire.ConsumeTag(data)
		if err := protowire.ParseError(n); err != nil {
			return err
		}
		data = data[n:]
		switch num {
		case 1:
			s, n := consumeString(data, typ)
			m.Input = s
			data = data[n:]
		case 2:
			s, n := consumeString(data, typ)
			m.Kind = s
			data = data[n:]
		case 3:
			s, n := consumeString(data, typ)
			m.CorrelationId = s
			data = data[n:]
		case 4:
			s, n := consumeString(data, typ)
			m.Tenant = s
			data = data[n:]
		default:
			n := protowire.ConsumeFieldValue(num, typ, data)
			if err := protowire.ParseError(n); err != nil {
				return err
			}
			data = data[n:]
		}
	}
	return nil
}

// MediaScoreRequest carries metadata about a media file for ML classification.
// Raw bytes are NOT sent over gRPC — the Go side hashes the file and sends
// the hash + extracted features only (privacy-by-design).
type MediaScoreRequest struct {
	FileHash           string
	MimeType           string
	FileSize           int64
	HasC2PaManifest    bool
	C2PaSignatureValid bool
	CorrelationId      string
	Tenant             string
}

func (m *MediaScoreRequest) Reset() { *m = MediaScoreRequest{} }
func (m *MediaScoreRequest) String() string {
	return fmt.Sprintf("MediaScoreRequest{hash=%q, mime=%q, size=%d, corr=%q, tenant=%q}",
		m.FileHash, m.MimeType, m.FileSize, m.CorrelationId, m.Tenant)
}
func (*MediaScoreRequest) ProtoMessage() {}

func (m *MediaScoreRequest) MarshalVT() ([]byte, error) {
	var b []byte
	b = appendString(b, 1, m.FileHash)
	b = appendString(b, 2, m.MimeType)
	b = appendVarint(b, 3, uint64(m.FileSize))
	if m.HasC2PaManifest {
		b = appendVarint(b, 4, 1)
	}
	if m.C2PaSignatureValid {
		b = appendVarint(b, 5, 1)
	}
	b = appendString(b, 6, m.CorrelationId)
	b = appendString(b, 7, m.Tenant)
	return b, nil
}

func (m *MediaScoreRequest) UnmarshalVT(data []byte) error {
	for len(data) > 0 {
		num, typ, n := protowire.ConsumeTag(data)
		if err := protowire.ParseError(n); err != nil {
			return err
		}
		data = data[n:]
		switch num {
		case 1:
			s, n := consumeString(data, typ)
			m.FileHash = s
			data = data[n:]
		case 2:
			s, n := consumeString(data, typ)
			m.MimeType = s
			data = data[n:]
		case 3:
			v, n := consumeVarint(data, typ)
			m.FileSize = int64(v)
			data = data[n:]
		case 4:
			v, n := consumeVarint(data, typ)
			m.HasC2PaManifest = v != 0
			data = data[n:]
		case 5:
			v, n := consumeVarint(data, typ)
			m.C2PaSignatureValid = v != 0
			data = data[n:]
		case 6:
			s, n := consumeString(data, typ)
			m.CorrelationId = s
			data = data[n:]
		case 7:
			s, n := consumeString(data, typ)
			m.Tenant = s
			data = data[n:]
		default:
			n := protowire.ConsumeFieldValue(num, typ, data)
			if err := protowire.ParseError(n); err != nil {
				return err
			}
			data = data[n:]
		}
	}
	return nil
}

func (m *MediaScoreRequest) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}
func (m *MediaScoreRequest) GetMimeType() string {
	if m != nil {
		return m.MimeType
	}
	return ""
}
func (m *MediaScoreRequest) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}
func (m *MediaScoreRequest) GetHasC2PaManifest() bool {
	if m != nil {
		return m.HasC2PaManifest
	}
	return false
}
func (m *MediaScoreRequest) GetC2PaSignatureValid() bool {
	if m != nil {
		return m.C2PaSignatureValid
	}
	return false
}
func (m *MediaScoreRequest) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}
func (m *MediaScoreRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

// IdentityScoreRequest carries extracted identity claim features for ML.
// Raw PII is NOT sent — only derived, non-reversible signals.
type IdentityScoreRequest struct {
	ClaimType              string
	Context                string
	NameTokenCount         int32
	EmailDomainIsDisposable bool
	IdFormatValid          bool
	IssuerCountry          string
	HasDob                 bool
	ReplayCount            int32
	CorrelationId          string
	Tenant                 string
}

func (m *IdentityScoreRequest) Reset() { *m = IdentityScoreRequest{} }
func (m *IdentityScoreRequest) String() string {
	return fmt.Sprintf("IdentityScoreRequest{claim_type=%q, context=%q, corr=%q, tenant=%q}",
		m.ClaimType, m.Context, m.CorrelationId, m.Tenant)
}
func (*IdentityScoreRequest) ProtoMessage() {}

func (m *IdentityScoreRequest) MarshalVT() ([]byte, error) {
	var b []byte
	b = appendString(b, 1, m.ClaimType)
	b = appendString(b, 2, m.Context)
	b = appendVarint(b, 3, uint64(m.NameTokenCount))
	if m.EmailDomainIsDisposable {
		b = appendVarint(b, 4, 1)
	}
	if m.IdFormatValid {
		b = appendVarint(b, 5, 1)
	}
	b = appendString(b, 6, m.IssuerCountry)
	if m.HasDob {
		b = appendVarint(b, 7, 1)
	}
	b = appendVarint(b, 8, uint64(m.ReplayCount))
	b = appendString(b, 9, m.CorrelationId)
	b = appendString(b, 10, m.Tenant)
	return b, nil
}

func (m *IdentityScoreRequest) UnmarshalVT(data []byte) error {
	for len(data) > 0 {
		num, typ, n := protowire.ConsumeTag(data)
		if err := protowire.ParseError(n); err != nil {
			return err
		}
		data = data[n:]
		switch num {
		case 1:
			s, n := consumeString(data, typ)
			m.ClaimType = s
			data = data[n:]
		case 2:
			s, n := consumeString(data, typ)
			m.Context = s
			data = data[n:]
		case 3:
			v, n := consumeVarint(data, typ)
			m.NameTokenCount = int32(v)
			data = data[n:]
		case 4:
			v, n := consumeVarint(data, typ)
			m.EmailDomainIsDisposable = v != 0
			data = data[n:]
		case 5:
			v, n := consumeVarint(data, typ)
			m.IdFormatValid = v != 0
			data = data[n:]
		case 6:
			s, n := consumeString(data, typ)
			m.IssuerCountry = s
			data = data[n:]
		case 7:
			v, n := consumeVarint(data, typ)
			m.HasDob = v != 0
			data = data[n:]
		case 8:
			v, n := consumeVarint(data, typ)
			m.ReplayCount = int32(v)
			data = data[n:]
		case 9:
			s, n := consumeString(data, typ)
			m.CorrelationId = s
			data = data[n:]
		case 10:
			s, n := consumeString(data, typ)
			m.Tenant = s
			data = data[n:]
		default:
			n := protowire.ConsumeFieldValue(num, typ, data)
			if err := protowire.ParseError(n); err != nil {
				return err
			}
			data = data[n:]
		}
	}
	return nil
}

func (m *IdentityScoreRequest) GetClaimType() string {
	if m != nil {
		return m.ClaimType
	}
	return ""
}
func (m *IdentityScoreRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}
func (m *IdentityScoreRequest) GetNameTokenCount() int32 {
	if m != nil {
		return m.NameTokenCount
	}
	return 0
}
func (m *IdentityScoreRequest) GetEmailDomainIsDisposable() bool {
	if m != nil {
		return m.EmailDomainIsDisposable
	}
	return false
}
func (m *IdentityScoreRequest) GetIdFormatValid() bool {
	if m != nil {
		return m.IdFormatValid
	}
	return false
}
func (m *IdentityScoreRequest) GetIssuerCountry() string {
	if m != nil {
		return m.IssuerCountry
	}
	return ""
}
func (m *IdentityScoreRequest) GetHasDob() bool {
	if m != nil {
		return m.HasDob
	}
	return false
}
func (m *IdentityScoreRequest) GetReplayCount() int32 {
	if m != nil {
		return m.ReplayCount
	}
	return 0
}
func (m *IdentityScoreRequest) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}
func (m *IdentityScoreRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

// AudioScoreRequest carries MFCC and spectral fingerprints for voice clone
// detection. Raw audio bytes are NOT sent (privacy-by-design).
type AudioScoreRequest struct {
	SessionId     string
	MfccHash      []byte
	SpectralHash  []byte
	DurationMs    float32
	VoiceDetected bool
	CorrelationId string
	Tenant        string
}

func (m *AudioScoreRequest) Reset() { *m = AudioScoreRequest{} }
func (m *AudioScoreRequest) String() string {
	return fmt.Sprintf("AudioScoreRequest{session=%q, duration_ms=%.1f, voice=%v, corr=%q, tenant=%q}",
		m.SessionId, m.DurationMs, m.VoiceDetected, m.CorrelationId, m.Tenant)
}
func (*AudioScoreRequest) ProtoMessage() {}

func (m *AudioScoreRequest) MarshalVT() ([]byte, error) {
	var b []byte
	b = appendString(b, 1, m.SessionId)
	if len(m.MfccHash) > 0 {
		b = appendBytes(b, 2, m.MfccHash)
	}
	if len(m.SpectralHash) > 0 {
		b = appendBytes(b, 3, m.SpectralHash)
	}
	if m.DurationMs != 0 {
		b = appendFloat32(b, 4, m.DurationMs)
	}
	if m.VoiceDetected {
		b = appendVarint(b, 5, 1)
	}
	b = appendString(b, 6, m.CorrelationId)
	b = appendString(b, 7, m.Tenant)
	return b, nil
}

func (m *AudioScoreRequest) UnmarshalVT(data []byte) error {
	for len(data) > 0 {
		num, typ, n := protowire.ConsumeTag(data)
		if err := protowire.ParseError(n); err != nil {
			return err
		}
		data = data[n:]
		switch num {
		case 1:
			s, n := consumeString(data, typ)
			m.SessionId = s
			data = data[n:]
		case 2:
			raw, n := consumeBytes(data, typ)
			m.MfccHash = raw
			data = data[n:]
		case 3:
			raw, n := consumeBytes(data, typ)
			m.SpectralHash = raw
			data = data[n:]
		case 4:
			f, n := consumeFloat32(data, typ)
			m.DurationMs = f
			data = data[n:]
		case 5:
			v, n := consumeVarint(data, typ)
			m.VoiceDetected = v != 0
			data = data[n:]
		case 6:
			s, n := consumeString(data, typ)
			m.CorrelationId = s
			data = data[n:]
		case 7:
			s, n := consumeString(data, typ)
			m.Tenant = s
			data = data[n:]
		default:
			n := protowire.ConsumeFieldValue(num, typ, data)
			if err := protowire.ParseError(n); err != nil {
				return err
			}
			data = data[n:]
		}
	}
	return nil
}

func (m *AudioScoreRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}
func (m *AudioScoreRequest) GetMfccHash() []byte {
	if m != nil {
		return m.MfccHash
	}
	return nil
}
func (m *AudioScoreRequest) GetSpectralHash() []byte {
	if m != nil {
		return m.SpectralHash
	}
	return nil
}
func (m *AudioScoreRequest) GetDurationMs() float32 {
	if m != nil {
		return m.DurationMs
	}
	return 0
}
func (m *AudioScoreRequest) GetVoiceDetected() bool {
	if m != nil {
		return m.VoiceDetected
	}
	return false
}
func (m *AudioScoreRequest) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}
func (m *AudioScoreRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

// VideoFrameRequest is one frame of a video call sent for deepfake analysis.
// Raw pixels are NOT sent — a compact feature vector is extracted Go-side.
type VideoFrameRequest struct {
	SessionId     string
	FrameSeq      int64
	FrameTsMs     int64
	FeatureVector []byte
	FaceDetected  bool
	CorrelationId string
	Tenant        string
}

func (m *VideoFrameRequest) Reset() { *m = VideoFrameRequest{} }
func (m *VideoFrameRequest) String() string {
	return fmt.Sprintf("VideoFrameRequest{session=%q, seq=%d, corr=%q, tenant=%q}",
		m.SessionId, m.FrameSeq, m.CorrelationId, m.Tenant)
}
func (*VideoFrameRequest) ProtoMessage() {}

func (m *VideoFrameRequest) MarshalVT() ([]byte, error) {
	var b []byte
	b = appendString(b, 1, m.SessionId)
	b = appendVarint(b, 2, uint64(m.FrameSeq))
	b = appendVarint(b, 3, uint64(m.FrameTsMs))
	if len(m.FeatureVector) > 0 {
		b = appendBytes(b, 4, m.FeatureVector)
	}
	if m.FaceDetected {
		b = appendVarint(b, 5, 1)
	}
	b = appendString(b, 6, m.CorrelationId)
	b = appendString(b, 7, m.Tenant)
	return b, nil
}

func (m *VideoFrameRequest) UnmarshalVT(data []byte) error {
	for len(data) > 0 {
		num, typ, n := protowire.ConsumeTag(data)
		if err := protowire.ParseError(n); err != nil {
			return err
		}
		data = data[n:]
		switch num {
		case 1:
			s, n := consumeString(data, typ)
			m.SessionId = s
			data = data[n:]
		case 2:
			v, n := consumeVarint(data, typ)
			m.FrameSeq = int64(v)
			data = data[n:]
		case 3:
			v, n := consumeVarint(data, typ)
			m.FrameTsMs = int64(v)
			data = data[n:]
		case 4:
			raw, n := consumeBytes(data, typ)
			m.FeatureVector = raw
			data = data[n:]
		case 5:
			v, n := consumeVarint(data, typ)
			m.FaceDetected = v != 0
			data = data[n:]
		case 6:
			s, n := consumeString(data, typ)
			m.CorrelationId = s
			data = data[n:]
		case 7:
			s, n := consumeString(data, typ)
			m.Tenant = s
			data = data[n:]
		default:
			n := protowire.ConsumeFieldValue(num, typ, data)
			if err := protowire.ParseError(n); err != nil {
				return err
			}
			data = data[n:]
		}
	}
	return nil
}

func (m *VideoFrameRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}
func (m *VideoFrameRequest) GetFrameSeq() int64 {
	if m != nil {
		return m.FrameSeq
	}
	return 0
}
func (m *VideoFrameRequest) GetFrameTsMs() int64 {
	if m != nil {
		return m.FrameTsMs
	}
	return 0
}
func (m *VideoFrameRequest) GetFeatureVector() []byte {
	if m != nil {
		return m.FeatureVector
	}
	return nil
}
func (m *VideoFrameRequest) GetFaceDetected() bool {
	if m != nil {
		return m.FaceDetected
	}
	return false
}
func (m *VideoFrameRequest) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}
func (m *VideoFrameRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

// VideoScoreEvent is the per-frame deepfake verdict returned by the server.
type VideoScoreEvent struct {
	SessionId    string
	FrameSeq     int64
	Confidence   float64
	Verdict      string
	LatencyMs    float64
	ModelVersion string
}

func (m *VideoScoreEvent) Reset() { *m = VideoScoreEvent{} }
func (m *VideoScoreEvent) String() string {
	return fmt.Sprintf("VideoScoreEvent{session=%q, seq=%d, verdict=%q, conf=%.3f}",
		m.SessionId, m.FrameSeq, m.Verdict, m.Confidence)
}
func (*VideoScoreEvent) ProtoMessage() {}

func (m *VideoScoreEvent) MarshalVT() ([]byte, error) {
	var b []byte
	b = appendString(b, 1, m.SessionId)
	b = appendVarint(b, 2, uint64(m.FrameSeq))
	b = appendDouble(b, 3, m.Confidence)
	b = appendString(b, 4, m.Verdict)
	b = appendDouble(b, 5, m.LatencyMs)
	b = appendString(b, 6, m.ModelVersion)
	return b, nil
}

func (m *VideoScoreEvent) UnmarshalVT(data []byte) error {
	for len(data) > 0 {
		num, typ, n := protowire.ConsumeTag(data)
		if err := protowire.ParseError(n); err != nil {
			return err
		}
		data = data[n:]
		switch num {
		case 1:
			s, n := consumeString(data, typ)
			m.SessionId = s
			data = data[n:]
		case 2:
			v, n := consumeVarint(data, typ)
			m.FrameSeq = int64(v)
			data = data[n:]
		case 3:
			f, n := consumeDouble(data, typ)
			m.Confidence = f
			data = data[n:]
		case 4:
			s, n := consumeString(data, typ)
			m.Verdict = s
			data = data[n:]
		case 5:
			f, n := consumeDouble(data, typ)
			m.LatencyMs = f
			data = data[n:]
		case 6:
			s, n := consumeString(data, typ)
			m.ModelVersion = s
			data = data[n:]
		default:
			n := protowire.ConsumeFieldValue(num, typ, data)
			if err := protowire.ParseError(n); err != nil {
				return err
			}
			data = data[n:]
		}
	}
	return nil
}

func (m *VideoScoreEvent) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}
func (m *VideoScoreEvent) GetFrameSeq() int64 {
	if m != nil {
		return m.FrameSeq
	}
	return 0
}
func (m *VideoScoreEvent) GetConfidence() float64 {
	if m != nil {
		return m.Confidence
	}
	return 0
}
func (m *VideoScoreEvent) GetVerdict() string {
	if m != nil {
		return m.Verdict
	}
	return ""
}
func (m *VideoScoreEvent) GetLatencyMs() float64 {
	if m != nil {
		return m.LatencyMs
	}
	return 0
}
func (m *VideoScoreEvent) GetModelVersion() string {
	if m != nil {
		return m.ModelVersion
	}
	return ""
}

// FeatureWeight names a feature and its attributed weight.
type FeatureWeight struct {
	Name   string
	Weight float64
}

func (m *FeatureWeight) Reset()         { *m = FeatureWeight{} }
func (m *FeatureWeight) String() string { return fmt.Sprintf("FeatureWeight{%q=%.3f}", m.Name, m.Weight) }
func (*FeatureWeight) ProtoMessage()    {}

func (m *FeatureWeight) MarshalVT() ([]byte, error) {
	var b []byte
	b = appendString(b, 1, m.Name)
	b = appendDouble(b, 2, m.Weight)
	return b, nil
}

func (m *FeatureWeight) UnmarshalVT(data []byte) error {
	for len(data) > 0 {
		num, typ, n := protowire.ConsumeTag(data)
		if err := protowire.ParseError(n); err != nil {
			return err
		}
		data = data[n:]
		switch num {
		case 1:
			s, n := consumeString(data, typ)
			m.Name = s
			data = data[n:]
		case 2:
			f, n := consumeDouble(data, typ)
			m.Weight = f
			data = data[n:]
		default:
			n := protowire.ConsumeFieldValue(num, typ, data)
			if err := protowire.ParseError(n); err != nil {
				return err
			}
			data = data[n:]
		}
	}
	return nil
}

// ScoreResponse is the unified shape returned by both score RPCs.
type ScoreResponse struct {
	Confidence   float64
	Verdict      string
	TopFeatures  []*FeatureWeight
	LatencyMs    float64
	ModelVersion string
	InputHash    string
}

func (m *ScoreResponse) Reset() { *m = ScoreResponse{} }
func (m *ScoreResponse) String() string {
	return fmt.Sprintf("ScoreResponse{verdict=%q, conf=%.3f, model=%q}",
		m.Verdict, m.Confidence, m.ModelVersion)
}
func (*ScoreResponse) ProtoMessage() {}

func (m *ScoreResponse) MarshalVT() ([]byte, error) {
	var b []byte
	b = appendDouble(b, 1, m.Confidence)
	b = appendString(b, 2, m.Verdict)
	for _, f := range m.TopFeatures {
		fb, err := f.MarshalVT()
		if err != nil {
			return nil, err
		}
		b = appendBytes(b, 3, fb)
	}
	b = appendDouble(b, 4, m.LatencyMs)
	b = appendString(b, 5, m.ModelVersion)
	b = appendString(b, 6, m.InputHash)
	return b, nil
}

func (m *ScoreResponse) UnmarshalVT(data []byte) error {
	for len(data) > 0 {
		num, typ, n := protowire.ConsumeTag(data)
		if err := protowire.ParseError(n); err != nil {
			return err
		}
		data = data[n:]
		switch num {
		case 1:
			f, n := consumeDouble(data, typ)
			m.Confidence = f
			data = data[n:]
		case 2:
			s, n := consumeString(data, typ)
			m.Verdict = s
			data = data[n:]
		case 3:
			raw, n := consumeMessage(data, typ)
			fw := &FeatureWeight{}
			if err := fw.UnmarshalVT(raw); err != nil {
				return err
			}
			m.TopFeatures = append(m.TopFeatures, fw)
			data = data[n:]
		case 4:
			f, n := consumeDouble(data, typ)
			m.LatencyMs = f
			data = data[n:]
		case 5:
			s, n := consumeString(data, typ)
			m.ModelVersion = s
			data = data[n:]
		case 6:
			s, n := consumeString(data, typ)
			m.InputHash = s
			data = data[n:]
		default:
			n := protowire.ConsumeFieldValue(num, typ, data)
			if err := protowire.ParseError(n); err != nil {
				return err
			}
			data = data[n:]
		}
	}
	return nil
}

// ModelInfoRequest is empty — ModelInfo is a poll-style endpoint.
type ModelInfoRequest struct{}

func (m *ModelInfoRequest) Reset()                    { *m = ModelInfoRequest{} }
func (m *ModelInfoRequest) String() string            { return "ModelInfoRequest{}" }
func (*ModelInfoRequest) ProtoMessage()               {}
func (m *ModelInfoRequest) MarshalVT() ([]byte, error) { return nil, nil }
func (m *ModelInfoRequest) UnmarshalVT(data []byte) error {
	for len(data) > 0 {
		num, typ, n := protowire.ConsumeTag(data)
		if err := protowire.ParseError(n); err != nil {
			return err
		}
		data = data[n:]
		nn := protowire.ConsumeFieldValue(num, typ, data)
		if err := protowire.ParseError(nn); err != nil {
			return err
		}
		data = data[nn:]
	}
	return nil
}

// ModelInfoResponse describes the currently loaded model.
type ModelInfoResponse struct {
	Name            string
	Version         string
	TrainingSummary string
	LoadedAt        int64
	Backend         string
	EvalMetricsJson string
}

func (m *ModelInfoResponse) Reset() { *m = ModelInfoResponse{} }
func (m *ModelInfoResponse) String() string {
	return fmt.Sprintf("ModelInfoResponse{name=%q, version=%q, backend=%q}",
		m.Name, m.Version, m.Backend)
}
func (*ModelInfoResponse) ProtoMessage() {}

func (m *ModelInfoResponse) MarshalVT() ([]byte, error) {
	var b []byte
	b = appendString(b, 1, m.Name)
	b = appendString(b, 2, m.Version)
	b = appendString(b, 3, m.TrainingSummary)
	b = appendVarint(b, 4, uint64(m.LoadedAt))
	b = appendString(b, 5, m.Backend)
	b = appendString(b, 6, m.EvalMetricsJson)
	return b, nil
}

func (m *ModelInfoResponse) UnmarshalVT(data []byte) error {
	for len(data) > 0 {
		num, typ, n := protowire.ConsumeTag(data)
		if err := protowire.ParseError(n); err != nil {
			return err
		}
		data = data[n:]
		switch num {
		case 1:
			s, n := consumeString(data, typ)
			m.Name = s
			data = data[n:]
		case 2:
			s, n := consumeString(data, typ)
			m.Version = s
			data = data[n:]
		case 3:
			s, n := consumeString(data, typ)
			m.TrainingSummary = s
			data = data[n:]
		case 4:
			v, n := consumeVarint(data, typ)
			m.LoadedAt = int64(v)
			data = data[n:]
		case 5:
			s, n := consumeString(data, typ)
			m.Backend = s
			data = data[n:]
		case 6:
			s, n := consumeString(data, typ)
			m.EvalMetricsJson = s
			data = data[n:]
		default:
			n := protowire.ConsumeFieldValue(num, typ, data)
			if err := protowire.ParseError(n); err != nil {
				return err
			}
			data = data[n:]
		}
	}
	return nil
}

// ─── wire-format helpers ────────────────────────────────────────────

func appendString(b []byte, num protowire.Number, s string) []byte {
	if s == "" {
		return b
	}
	b = protowire.AppendTag(b, num, protowire.BytesType)
	b = protowire.AppendString(b, s)
	return b
}

func appendBytes(b []byte, num protowire.Number, v []byte) []byte {
	b = protowire.AppendTag(b, num, protowire.BytesType)
	b = protowire.AppendBytes(b, v)
	return b
}

func appendDouble(b []byte, num protowire.Number, f float64) []byte {
	if f == 0 {
		return b
	}
	b = protowire.AppendTag(b, num, protowire.Fixed64Type)
	b = protowire.AppendFixed64(b, math_Float64bits(f))
	return b
}

func appendVarint(b []byte, num protowire.Number, v uint64) []byte {
	if v == 0 {
		return b
	}
	b = protowire.AppendTag(b, num, protowire.VarintType)
	b = protowire.AppendVarint(b, v)
	return b
}

func consumeString(data []byte, typ protowire.Type) (string, int) {
	if typ != protowire.BytesType {
		n := protowire.ConsumeFieldValue(0, typ, data)
		return "", n
	}
	v, n := protowire.ConsumeString(data)
	return v, n
}

func consumeMessage(data []byte, typ protowire.Type) ([]byte, int) {
	if typ != protowire.BytesType {
		n := protowire.ConsumeFieldValue(0, typ, data)
		return nil, n
	}
	v, n := protowire.ConsumeBytes(data)
	return v, n
}

func consumeBytes(data []byte, typ protowire.Type) ([]byte, int) {
	if typ != protowire.BytesType {
		n := protowire.ConsumeFieldValue(0, typ, data)
		return nil, n
	}
	v, n := protowire.ConsumeBytes(data)
	// Return a copy so the caller owns the slice independently of the
	// input buffer — matches proto3 semantics for bytes fields.
	out := make([]byte, len(v))
	copy(out, v)
	return out, n
}

func consumeDouble(data []byte, typ protowire.Type) (float64, int) {
	if typ != protowire.Fixed64Type {
		n := protowire.ConsumeFieldValue(0, typ, data)
		return 0, n
	}
	v, n := protowire.ConsumeFixed64(data)
	return math_Float64frombits(v), n
}

func consumeVarint(data []byte, typ protowire.Type) (uint64, int) {
	if typ != protowire.VarintType {
		n := protowire.ConsumeFieldValue(0, typ, data)
		return 0, n
	}
	v, n := protowire.ConsumeVarint(data)
	return v, n
}

func appendFloat32(b []byte, num protowire.Number, f float32) []byte {
	if f == 0 {
		return b
	}
	b = protowire.AppendTag(b, num, protowire.Fixed32Type)
	b = protowire.AppendFixed32(b, math_Float32bits(f))
	return b
}

func consumeFloat32(data []byte, typ protowire.Type) (float32, int) {
	if typ != protowire.Fixed32Type {
		n := protowire.ConsumeFieldValue(0, typ, data)
		return 0, n
	}
	v, n := protowire.ConsumeFixed32(data)
	return math_Float32frombits(v), n
}
