// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// 	protoc-gen-go-grpc    hand-written equivalent
// 	protoc                v3 (vertguard.ml.v1)
// source: proto/ml/v1/inference.proto
//
// WHY hand-written: see inference.pb.go header. The Invoke calls
// below match the wire path the Python service registers
// (`/vertguard.ml.v1.InferenceService/<method>`).

package mlpb

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// InferenceService_ServiceDesc fully-qualified service name.
const (
	InferenceService_ScorePrompt_FullMethodName      = "/vertguard.ml.v1.InferenceService/ScorePrompt"
	InferenceService_ScorePhishing_FullMethodName    = "/vertguard.ml.v1.InferenceService/ScorePhishing"
	InferenceService_ScoreMedia_FullMethodName       = "/vertguard.ml.v1.InferenceService/ScoreMedia"
	InferenceService_ScoreIdentity_FullMethodName    = "/vertguard.ml.v1.InferenceService/ScoreIdentity"
	InferenceService_ScoreAudio_FullMethodName       = "/vertguard.ml.v1.InferenceService/ScoreAudio"
	InferenceService_ScoreVideoStream_FullMethodName = "/vertguard.ml.v1.InferenceService/ScoreVideoStream"
	InferenceService_ModelInfo_FullMethodName        = "/vertguard.ml.v1.InferenceService/ModelInfo"
)

// InferenceServiceClient is the client API for InferenceService.
type InferenceServiceClient interface {
	ScorePrompt(ctx context.Context, in *PromptScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error)
	ScorePhishing(ctx context.Context, in *PhishingScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error)
	ScoreMedia(ctx context.Context, in *MediaScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error)
	ScoreIdentity(ctx context.Context, in *IdentityScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error)
	ScoreAudio(ctx context.Context, in *AudioScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error)
	ScoreVideoStream(ctx context.Context, opts ...grpc.CallOption) (InferenceService_ScoreVideoStreamClient, error)
	ModelInfo(ctx context.Context, in *ModelInfoRequest, opts ...grpc.CallOption) (*ModelInfoResponse, error)
}

type inferenceServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewInferenceServiceClient binds a client to an existing gRPC connection.
func NewInferenceServiceClient(cc grpc.ClientConnInterface) InferenceServiceClient {
	return &inferenceServiceClient{cc}
}

func (c *inferenceServiceClient) ScorePrompt(ctx context.Context, in *PromptScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error) {
	out := new(ScoreResponse)
	// ForceCodec routes this RPC through our hand-written codec without
	// poisoning the global codec registry.
	opts = append([]grpc.CallOption{grpc.ForceCodec(Codec{})}, opts...)
	if err := c.cc.Invoke(ctx, InferenceService_ScorePrompt_FullMethodName, in, out, opts...); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceClient) ScorePhishing(ctx context.Context, in *PhishingScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error) {
	out := new(ScoreResponse)
	opts = append([]grpc.CallOption{grpc.ForceCodec(Codec{})}, opts...)
	if err := c.cc.Invoke(ctx, InferenceService_ScorePhishing_FullMethodName, in, out, opts...); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceClient) ScoreMedia(ctx context.Context, in *MediaScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error) {
	out := new(ScoreResponse)
	opts = append([]grpc.CallOption{grpc.ForceCodec(Codec{})}, opts...)
	if err := c.cc.Invoke(ctx, InferenceService_ScoreMedia_FullMethodName, in, out, opts...); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceClient) ScoreIdentity(ctx context.Context, in *IdentityScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error) {
	out := new(ScoreResponse)
	opts = append([]grpc.CallOption{grpc.ForceCodec(Codec{})}, opts...)
	if err := c.cc.Invoke(ctx, InferenceService_ScoreIdentity_FullMethodName, in, out, opts...); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceClient) ScoreAudio(ctx context.Context, in *AudioScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error) {
	out := new(ScoreResponse)
	opts = append([]grpc.CallOption{grpc.ForceCodec(Codec{})}, opts...)
	if err := c.cc.Invoke(ctx, InferenceService_ScoreAudio_FullMethodName, in, out, opts...); err != nil {
		return nil, err
	}
	return out, nil
}

// InferenceService_ScoreVideoStreamClient is the client-side stream handle
// for the bidirectional ScoreVideoStream RPC.
type InferenceService_ScoreVideoStreamClient interface {
	Send(*VideoFrameRequest) error
	Recv() (*VideoScoreEvent, error)
	grpc.ClientStream
}

type inferenceServiceScoreVideoStreamClient struct {
	grpc.ClientStream
}

func (x *inferenceServiceScoreVideoStreamClient) Send(m *VideoFrameRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *inferenceServiceScoreVideoStreamClient) Recv() (*VideoScoreEvent, error) {
	m := new(VideoScoreEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *inferenceServiceClient) ScoreVideoStream(ctx context.Context, opts ...grpc.CallOption) (InferenceService_ScoreVideoStreamClient, error) {
	opts = append([]grpc.CallOption{grpc.ForceCodec(Codec{})}, opts...)
	stream, err := c.cc.NewStream(ctx, &InferenceService_ServiceDesc.Streams[0], InferenceService_ScoreVideoStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	return &inferenceServiceScoreVideoStreamClient{stream}, nil
}

func (c *inferenceServiceClient) ModelInfo(ctx context.Context, in *ModelInfoRequest, opts ...grpc.CallOption) (*ModelInfoResponse, error) {
	out := new(ModelInfoResponse)
	opts = append([]grpc.CallOption{grpc.ForceCodec(Codec{})}, opts...)
	if err := c.cc.Invoke(ctx, InferenceService_ModelInfo_FullMethodName, in, out, opts...); err != nil {
		return nil, err
	}
	return out, nil
}

// InferenceService_ScoreVideoStreamServer is the server-side stream handle
// for the bidirectional ScoreVideoStream RPC.
type InferenceService_ScoreVideoStreamServer interface {
	Send(*VideoScoreEvent) error
	Recv() (*VideoFrameRequest, error)
	grpc.ServerStream
}

type inferenceServiceScoreVideoStreamServer struct {
	grpc.ServerStream
}

func (x *inferenceServiceScoreVideoStreamServer) Send(m *VideoScoreEvent) error {
	return x.ServerStream.SendMsg(m)
}

func (x *inferenceServiceScoreVideoStreamServer) Recv() (*VideoFrameRequest, error) {
	m := new(VideoFrameRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// InferenceServiceServer is the server API for InferenceService.
// Servers must implement these or embed UnimplementedInferenceServiceServer
// for forward-compatibility.
type InferenceServiceServer interface {
	ScorePrompt(context.Context, *PromptScoreRequest) (*ScoreResponse, error)
	ScorePhishing(context.Context, *PhishingScoreRequest) (*ScoreResponse, error)
	ScoreMedia(context.Context, *MediaScoreRequest) (*ScoreResponse, error)
	ScoreIdentity(context.Context, *IdentityScoreRequest) (*ScoreResponse, error)
	ScoreAudio(context.Context, *AudioScoreRequest) (*ScoreResponse, error)
	ScoreVideoStream(InferenceService_ScoreVideoStreamServer) error
	ModelInfo(context.Context, *ModelInfoRequest) (*ModelInfoResponse, error)
	mustEmbedUnimplementedInferenceServiceServer()
}

// UnimplementedInferenceServiceServer satisfies the contract with method
// stubs that return Unimplemented. Embed in concrete servers to stay
// forward-compatible if new RPCs are added to the proto.
type UnimplementedInferenceServiceServer struct{}

func (UnimplementedInferenceServiceServer) ScorePrompt(context.Context, *PromptScoreRequest) (*ScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScorePrompt not implemented")
}
func (UnimplementedInferenceServiceServer) ScorePhishing(context.Context, *PhishingScoreRequest) (*ScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScorePhishing not implemented")
}
func (UnimplementedInferenceServiceServer) ScoreMedia(context.Context, *MediaScoreRequest) (*ScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScoreMedia not implemented")
}
func (UnimplementedInferenceServiceServer) ScoreIdentity(context.Context, *IdentityScoreRequest) (*ScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScoreIdentity not implemented")
}
func (UnimplementedInferenceServiceServer) ScoreAudio(context.Context, *AudioScoreRequest) (*ScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScoreAudio not implemented")
}
func (UnimplementedInferenceServiceServer) ScoreVideoStream(InferenceService_ScoreVideoStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ScoreVideoStream not implemented")
}
func (UnimplementedInferenceServiceServer) ModelInfo(context.Context, *ModelInfoRequest) (*ModelInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModelInfo not implemented")
}
func (UnimplementedInferenceServiceServer) mustEmbedUnimplementedInferenceServiceServer() {}

// RegisterInferenceServiceServer wires the server impl into a gRPC server.
func RegisterInferenceServiceServer(s grpc.ServiceRegistrar, srv InferenceServiceServer) {
	s.RegisterService(&InferenceService_ServiceDesc, srv)
}

func _InferenceService_ScorePrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromptScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).ScorePrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: InferenceService_ScorePrompt_FullMethodName}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).ScorePrompt(ctx, req.(*PromptScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceService_ScorePhishing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhishingScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).ScorePhishing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: InferenceService_ScorePhishing_FullMethodName}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).ScorePhishing(ctx, req.(*PhishingScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceService_ScoreMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MediaScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).ScoreMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: InferenceService_ScoreMedia_FullMethodName}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).ScoreMedia(ctx, req.(*MediaScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceService_ScoreIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentityScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).ScoreIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: InferenceService_ScoreIdentity_FullMethodName}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).ScoreIdentity(ctx, req.(*IdentityScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceService_ScoreAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AudioScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).ScoreAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: InferenceService_ScoreAudio_FullMethodName}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).ScoreAudio(ctx, req.(*AudioScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceService_ScoreVideoStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InferenceServiceServer).ScoreVideoStream(&inferenceServiceScoreVideoStreamServer{stream})
}

func _InferenceService_ModelInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).ModelInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: InferenceService_ModelInfo_FullMethodName}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).ModelInfo(ctx, req.(*ModelInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InferenceService_ServiceDesc is the grpc.ServiceDesc registered with grpc.NewServer.
var InferenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vertguard.ml.v1.InferenceService",
	HandlerType: (*InferenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "ScorePrompt", Handler: _InferenceService_ScorePrompt_Handler},
		{MethodName: "ScorePhishing", Handler: _InferenceService_ScorePhishing_Handler},
		{MethodName: "ScoreMedia", Handler: _InferenceService_ScoreMedia_Handler},
		{MethodName: "ScoreIdentity", Handler: _InferenceService_ScoreIdentity_Handler},
		{MethodName: "ScoreAudio", Handler: _InferenceService_ScoreAudio_Handler},
		{MethodName: "ModelInfo", Handler: _InferenceService_ModelInfo_Handler},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ScoreVideoStream",
			Handler:       _InferenceService_ScoreVideoStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/ml/v1/inference.proto",
}
