{{- if and .Values.secret.create (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vertguard.fullname" . }}-secrets
  labels:
    {{- include "vertguard.labels" . | nindent 4 }}
type: Opaque
data:
  auth-secret: {{ .Values.secret.authSecret | b64enc | quote }}
  db-password: {{ default "" .Values.secret.dbPassword | b64enc | quote }}
  citadel-hmac-secret: {{ default "" .Values.secret.citadelHmacSecret | b64enc | quote }}
  threatflow-webhook-secret: {{ default "" .Values.secret.threatflowWebhookSecret | b64enc | quote }}
{{- end }}
