apiVersion: v1
kind: Service
metadata:
  name: {{ include "vertguard.fullname" . }}
  labels:
    {{- include "vertguard.labels" . | nindent 4 }}
  annotations:
    {{- if not .Values.metrics.serviceMonitor.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.port }}"
    prometheus.io/path: "/metrics"
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "vertguard.selectorLabels" . | nindent 4 }}
