apiVersion: v1
kind: ConfigMap
metadata:
  name: threatflow-config
  namespace: opensecstack
  labels:
    app: threatflow
    app.kubernetes.io/part-of: opensecstack
data:
  THREATFLOW_PORT: "8091"
  THREATFLOW_LOG_LEVEL: "info"
  THREATFLOW_LOG_FORMAT: "json"
  THREATFLOW_DB_MAX_OPEN_CONNS: "20"
  THREATFLOW_DB_MAX_IDLE_CONNS: "5"
  THREATFLOW_CITADEL_PROJECT_ID: "threatflow"
