apiVersion: v1
kind: Service
metadata:
  name: threatflow
  namespace: opensecstack
  labels:
    app: threatflow
    app.kubernetes.io/part-of: opensecstack
spec:
  type: ClusterIP
  selector:
    app: threatflow
  ports:
    - name: http
      port: 8091
      targetPort: http
      protocol: TCP
