FROM golang:1.25-alpine
RUN apk add --no-cache git ca-certificates tzdata wget && \
    go install github.com/air-verse/air@latest
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
EXPOSE 8090
CMD ["air", "-c", ".air.toml"]
