{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opencsirt.fullname" . }}-postgres
  labels:
    {{- include "opencsirt.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "opencsirt.fullname" . }}-postgres
  labels:
    {{- include "opencsirt.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  serviceName: {{ include "opencsirt.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "opencsirt.name" . }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "opencsirt.name" . }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "opencsirt.secretName" . }}
                  key: postgresPassword
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
          ports:
            - containerPort: 5432
              name: pg
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "opencsirt.fullname" . }}-postgres
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencsirt.fullname" . }}-postgres
  labels:
    {{- include "opencsirt.labels" . | nindent 4 }}
spec:
  ports:
    - port: 5432
      targetPort: pg
      name: pg
  selector:
    app.kubernetes.io/name: {{ include "opencsirt.name" . }}
    app.kubernetes.io/component: postgres
{{- end }}
