package modules

import (
	"context"
	"fmt"
	"strings"

	"github.com/rs/zerolog"

	"github.com/opensecstack/apiguard/internal/domain"
	"github.com/opensecstack/apiguard/internal/testgen"
)

// AuthModule implements OWASP API2:2023 Broken Authentication checks.
// It executes test cases generated by L2 (testgen) that probe for authentication
// vulnerabilities such as missing auth, expired tokens, invalid tokens, and
// unprotected state-changing endpoints.
type AuthModule struct {
	executor *HTTPExecutor
	logger   zerolog.Logger
}

// NewAuthModule creates a new AuthModule with the given HTTP executor and logger.
func NewAuthModule(executor *HTTPExecutor, logger zerolog.Logger) *AuthModule {
	return &AuthModule{
		executor: executor,
		logger:   logger.With().Str("module", "a2_auth").Logger(),
	}
}

// ID returns the unique identifier for this module.
func (m *AuthModule) ID() string { return "a2_auth" }

// Name returns the human-readable name of this module.
func (m *AuthModule) Name() string { return "Broken Authentication" }

// Execute runs all authentication test cases against the target API and returns
// any findings discovered. It handles auth_removal, auth_token_expired,
// auth_token_replay, invalid token, and suspicious unprotected endpoint categories.
func (m *AuthModule) Execute(ctx context.Context, cases []testgen.TestCase) ([]domain.Finding, error) {
	var findings []domain.Finding

	for _, tc := range cases {
		select {
		case <-ctx.Done():
			return findings, ctx.Err()
		default:
		}

		m.logger.Debug().
			Str("case_id", tc.ID).
			Str("category", tc.Category).
			Str("endpoint", tc.EndpointMethod+" "+tc.EndpointPath).
			Msg("executing test case")

		var caseFinding *domain.Finding
		var err error

		switch tc.Category {
		case "auth_removal":
			caseFinding, err = m.executeAuthRemoval(ctx, tc)
		case "auth_token_expired":
			caseFinding, err = m.executeExpiredToken(ctx, tc)
		case "auth_token_replay":
			caseFinding, err = m.executeTokenReplay(ctx, tc)
		case "auth_invalid_token":
			caseFinding, err = m.executeInvalidToken(ctx, tc)
		case "auth_unprotected_write":
			caseFinding, err = m.executeUnprotectedWrite(ctx, tc)
		default:
			m.logger.Warn().Str("category", tc.Category).Msg("unknown test case category, skipping")
			continue
		}

		if err != nil {
			m.logger.Error().Err(err).Str("case_id", tc.ID).Msg("test case execution failed")
			continue
		}

		if caseFinding != nil {
			findings = append(findings, *caseFinding)
		}
	}

	m.logger.Info().Int("findings", len(findings)).Int("cases", len(cases)).Msg("authentication module completed")
	return findings, nil
}

// executeAuthRemoval sends a request without any authentication headers.
// If the server responds with 2xx, the endpoint is accessible without auth (CRITICAL).
func (m *AuthModule) executeAuthRemoval(ctx context.Context, tc testgen.TestCase) (*domain.Finding, error) {
	req := m.findRequestByAuth(tc.Requests, "none")
	if req == nil {
		// Fall back to the first request, stripping auth
		if len(tc.Requests) == 0 {
			return nil, fmt.Errorf("no requests in test case %s", tc.ID)
		}
		stripped := tc.Requests[0]
		stripped.Auth = "none"
		stripped.Headers = removeAuthHeaders(stripped.Headers)
		req = &stripped
	}

	resp, err := m.executor.Do(ctx, *req)
	if err != nil {
		return nil, fmt.Errorf("request failed: %w", err)
	}

	endpoint := tc.EndpointMethod + " " + tc.EndpointPath

	if isSuccessStatus(resp.StatusCode) {
		m.logger.Warn().
			Str("endpoint", endpoint).
			Int("status", resp.StatusCode).
			Msg("endpoint accessible without authentication")

		return &domain.Finding{
			OWASPId:        "API2:2023",
			ModuleID:       "a2_auth",
			Title:          "Missing Authentication on " + endpoint,
			Description:    fmt.Sprintf("The endpoint %s returned HTTP %d without any authentication credentials. This means the endpoint is accessible to unauthenticated users.", endpoint, resp.StatusCode),
			Severity:       domain.SeverityCritical,
			CVSSScore:      9.1,
			CVSSVector:     "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
			EndpointPath:   tc.EndpointPath,
			EndpointMethod: tc.EndpointMethod,
			Evidence:       buildEvidence(req, resp),
			Remediation:    "Enforce authentication on all sensitive endpoints. Ensure auth middleware is applied before any business logic.",
			Status:         domain.FindingStatusOpen,
		}, nil
	}

	m.logger.Debug().Str("endpoint", endpoint).Int("status", resp.StatusCode).Msg("endpoint properly rejects unauthenticated requests")
	return nil, nil
}

// executeExpiredToken sends a request with an expired JWT token.
// If the server responds with 2xx, expired tokens are accepted (HIGH).
func (m *AuthModule) executeExpiredToken(ctx context.Context, tc testgen.TestCase) (*domain.Finding, error) {
	req := m.findRequestByAuth(tc.Requests, "expired")
	if req == nil {
		if len(tc.Requests) == 0 {
			return nil, fmt.Errorf("no requests in test case %s", tc.ID)
		}
		req = &tc.Requests[0]
	}

	resp, err := m.executor.Do(ctx, *req)
	if err != nil {
		return nil, fmt.Errorf("request failed: %w", err)
	}

	endpoint := tc.EndpointMethod + " " + tc.EndpointPath

	if isSuccessStatus(resp.StatusCode) {
		m.logger.Warn().
			Str("endpoint", endpoint).
			Int("status", resp.StatusCode).
			Msg("endpoint accepts expired tokens")

		return &domain.Finding{
			OWASPId:        "API2:2023",
			ModuleID:       "a2_auth",
			Title:          "Expired Token Accepted on " + endpoint,
			Description:    fmt.Sprintf("The endpoint %s returned HTTP %d when presented with an expired JWT token. The server is not validating token expiration.", endpoint, resp.StatusCode),
			Severity:       domain.SeverityHigh,
			CVSSScore:      7.4,
			CVSSVector:     "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
			EndpointPath:   tc.EndpointPath,
			EndpointMethod: tc.EndpointMethod,
			Evidence:       buildEvidence(req, resp),
			Remediation:    "Validate token expiration (exp claim) on every request. Reject tokens with expired timestamps.",
			Status:         domain.FindingStatusOpen,
		}, nil
	}

	m.logger.Debug().Str("endpoint", endpoint).Int("status", resp.StatusCode).Msg("endpoint properly rejects expired tokens")
	return nil, nil
}

// executeTokenReplay sends the same valid token twice in quick succession.
// This is informational — most stateless JWT APIs will accept replayed tokens.
// A finding is only generated if the test case explicitly expects anti-replay.
func (m *AuthModule) executeTokenReplay(ctx context.Context, tc testgen.TestCase) (*domain.Finding, error) {
	if len(tc.Requests) == 0 {
		return nil, fmt.Errorf("no requests in test case %s", tc.ID)
	}

	req := tc.Requests[0]

	// Send the request twice in succession
	resp1, err := m.executor.Do(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("first replay request failed: %w", err)
	}

	resp2, err := m.executor.Do(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("second replay request failed: %w", err)
	}

	endpoint := tc.EndpointMethod + " " + tc.EndpointPath

	// Only flag if the test case expected anti-replay and both requests succeeded
	if tc.Expected.ShouldSucceed == false && isSuccessStatus(resp1.StatusCode) && isSuccessStatus(resp2.StatusCode) {
		m.logger.Info().
			Str("endpoint", endpoint).
			Int("status_1", resp1.StatusCode).
			Int("status_2", resp2.StatusCode).
			Msg("token replay accepted — informational")

		return &domain.Finding{
			OWASPId:        "API2:2023",
			ModuleID:       "a2_auth",
			Title:          "Token Replay Accepted on " + endpoint,
			Description:    fmt.Sprintf("The endpoint %s accepted the same token in two consecutive requests (HTTP %d, %d). If anti-replay is expected, this is a vulnerability.", endpoint, resp1.StatusCode, resp2.StatusCode),
			Severity:       domain.SeverityInfo,
			CVSSScore:      0.0,
			CVSSVector:     "",
			EndpointPath:   tc.EndpointPath,
			EndpointMethod: tc.EndpointMethod,
			Evidence:       buildEvidence(&req, resp2),
			Remediation:    "Consider implementing token anti-replay mechanisms such as jti (JWT ID) claims with server-side tracking, or use short-lived tokens.",
			Status:         domain.FindingStatusOpen,
		}, nil
	}

	m.logger.Debug().Str("endpoint", endpoint).Msg("token replay check completed — no finding")
	return nil, nil
}

// executeInvalidToken sends a request with a malformed/invalid token.
// If the server responds with 2xx, invalid tokens are accepted (CRITICAL).
func (m *AuthModule) executeInvalidToken(ctx context.Context, tc testgen.TestCase) (*domain.Finding, error) {
	req := m.findRequestByAuth(tc.Requests, "invalid")
	if req == nil {
		if len(tc.Requests) == 0 {
			return nil, fmt.Errorf("no requests in test case %s", tc.ID)
		}
		req = &tc.Requests[0]
	}

	resp, err := m.executor.Do(ctx, *req)
	if err != nil {
		return nil, fmt.Errorf("request failed: %w", err)
	}

	endpoint := tc.EndpointMethod + " " + tc.EndpointPath

	if isSuccessStatus(resp.StatusCode) {
		m.logger.Warn().
			Str("endpoint", endpoint).
			Int("status", resp.StatusCode).
			Msg("endpoint accepts invalid tokens")

		return &domain.Finding{
			OWASPId:        "API2:2023",
			ModuleID:       "a2_auth",
			Title:          "Invalid Token Accepted on " + endpoint,
			Description:    fmt.Sprintf("The endpoint %s returned HTTP %d when presented with a malformed token. The server is not properly validating token signatures or format.", endpoint, resp.StatusCode),
			Severity:       domain.SeverityCritical,
			CVSSScore:      9.1,
			CVSSVector:     "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
			EndpointPath:   tc.EndpointPath,
			EndpointMethod: tc.EndpointMethod,
			Evidence:       buildEvidence(req, resp),
			Remediation:    "Validate token signatures and format. Reject malformed or unsigned tokens.",
			Status:         domain.FindingStatusOpen,
		}, nil
	}

	m.logger.Debug().Str("endpoint", endpoint).Int("status", resp.StatusCode).Msg("endpoint properly rejects invalid tokens")
	return nil, nil
}

// executeUnprotectedWrite sends a state-changing request (POST/PUT/PATCH/DELETE) without auth.
// If the server responds with 2xx, the write endpoint lacks authentication (MEDIUM).
func (m *AuthModule) executeUnprotectedWrite(ctx context.Context, tc testgen.TestCase) (*domain.Finding, error) {
	req := m.findRequestByAuth(tc.Requests, "none")
	if req == nil {
		if len(tc.Requests) == 0 {
			return nil, fmt.Errorf("no requests in test case %s", tc.ID)
		}
		stripped := tc.Requests[0]
		stripped.Auth = "none"
		stripped.Headers = removeAuthHeaders(stripped.Headers)
		req = &stripped
	}

	resp, err := m.executor.Do(ctx, *req)
	if err != nil {
		return nil, fmt.Errorf("request failed: %w", err)
	}

	method := tc.EndpointMethod
	path := tc.EndpointPath
	endpoint := method + " " + path

	if isSuccessStatus(resp.StatusCode) {
		m.logger.Warn().
			Str("endpoint", endpoint).
			Int("status", resp.StatusCode).
			Msg("unprotected state-changing endpoint detected")

		return &domain.Finding{
			OWASPId:        "API2:2023",
			ModuleID:       "a2_auth",
			Title:          "Unprotected State-Changing Endpoint: " + method + " " + path,
			Description:    fmt.Sprintf("The state-changing endpoint %s returned HTTP %d without authentication. While the OpenAPI spec did not declare security for this endpoint, state-changing operations should typically require authentication.", endpoint, resp.StatusCode),
			Severity:       domain.SeverityMedium,
			CVSSScore:      5.3,
			CVSSVector:     "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
			EndpointPath:   path,
			EndpointMethod: method,
			Evidence:       buildEvidence(req, resp),
			Remediation:    "Review whether this endpoint should require authentication. State-changing operations (POST/PUT/PATCH/DELETE) typically need auth.",
			Status:         domain.FindingStatusOpen,
		}, nil
	}

	m.logger.Debug().Str("endpoint", endpoint).Int("status", resp.StatusCode).Msg("state-changing endpoint properly protected")
	return nil, nil
}

// findRequestByAuth returns the first TestRequest whose Auth field matches the given value.
// Returns nil if no matching request is found.
func (m *AuthModule) findRequestByAuth(requests []testgen.TestRequest, auth string) *testgen.TestRequest {
	for i := range requests {
		if requests[i].Auth == auth {
			return &requests[i]
		}
	}
	return nil
}

// isSuccessStatus returns true if the HTTP status code is in the 2xx range.
func isSuccessStatus(code int) bool {
	return code >= 200 && code < 300
}

// removeAuthHeaders strips Authorization and related auth headers from the header list.
func removeAuthHeaders(headers [][]string) [][]string {
	var filtered [][]string
	for _, h := range headers {
		if len(h) < 2 {
			continue
		}
		name := strings.ToLower(h[0])
		if name == "authorization" || name == "x-api-key" || name == "x-auth-token" {
			continue
		}
		filtered = append(filtered, h)
	}
	return filtered
}

// buildEvidence creates an Evidence struct from the test request and response.
func buildEvidence(req *testgen.TestRequest, resp *HTTPResponse) domain.Evidence {
	requestStr := fmt.Sprintf("%s %s", req.Method, req.Path)
	for _, h := range req.Headers {
		if len(h) >= 2 {
			requestStr += fmt.Sprintf("\n%s: %s", h[0], h[1])
		}
	}
	if len(req.Body) > 0 {
		requestStr += fmt.Sprintf("\n\n%s", string(req.Body))
	}

	responseStr := fmt.Sprintf("HTTP %d\n%s", resp.StatusCode, string(resp.Body))

	detail := map[string]interface{}{
		"auth_type":   req.Auth,
		"status_code": resp.StatusCode,
	}

	return domain.Evidence{
		Request:  requestStr,
		Response: responseStr,
		Detail:   detail,
	}
}
