// IPC protocol types shared between the Go API (unix socket client)
// and the Rust sandbox host (unix socket server).
// All messages are newline-delimited JSON on the socket.

use serde::{Deserialize, Serialize};

/// Request to start a new lab session.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StartRequest {
    /// Opaque session identifier generated by the Go API.
    pub session_id: String,
    /// Lab definition ID (matches `lab_definitions.id` in the DB).
    pub lab_id: String,
    /// OCI image reference including digest, e.g.
    /// `ghcr.io/opensecstack/cyberpath-labs/phish-classify-1@sha256:...`
    pub lab_image: String,
}

/// Response to a StartRequest.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StartResponse {
    pub session_id: String,
    /// "starting" | "running" | "error"
    pub status: String,
    /// Port on localhost where the xterm.js WebSocket relay listens
    /// for this session.  0 if the session failed to start.
    pub ws_relay_port: u16,
}

/// Request to stop a running lab session.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StopRequest {
    pub session_id: String,
}

/// Response to a StopRequest.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StopResponse {
    pub session_id: String,
    /// "stopped" | "not_found" | "error"
    pub status: String,
}

/// Top-level envelope so a single socket can carry multiple request kinds.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Request {
    Start(StartRequest),
    Stop(StopRequest),
}

/// Top-level response envelope.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Response {
    Start(StartResponse),
    Stop(StopResponse),
}
