import DocsLayout from '../DocsLayout'
import CodeBlock from '../../../components/CodeBlock'

const toc = [
  { id: 'overview', label: 'Overview' },
  { id: 'key-features', label: 'Key features' },
  { id: 'architecture', label: 'Architecture' },
  { id: 'ports-endpoints', label: 'Ports & endpoints' },
  { id: 'integration', label: 'Integration' },
  { id: 'full-documentation', label: 'Full documentation' },
]

export default function OpenCsirtPage() {
  return (
    <DocsLayout
      breadcrumbs={['Docs', 'Platforms', 'OpenCSIRT']}
      toc={toc}
      editPath="platforms/OpenCsirtPage.tsx"
      prev={{ label: 'SecureLab', path: '/docs/platforms/securelab' }}
      next={{ label: 'VertGuard', path: '/docs/platforms/vertguard' }}
    >
      <h1>OpenCSIRT</h1>
      <p>
        <strong>OpenCSIRT</strong> is the governance-tier CSIRT operations platform in the
        opensecstack ecosystem. It gives a national or sector CSIRT a single working surface
        for constituency tracking, incident coordination, CSAF 2.0 advisory authoring, and
        federated peer trust — all with every privileged action attested by{' '}
        <a href="/docs/governance">CITADEL</a>.
      </p>
      <p>
        Version <strong>v1.0.0</strong> (shipped 2026-05-10) is feature complete across all
        11 modules. License: <strong>AGPL-3.0-or-later</strong> (governance tier).
      </p>

      <h2 id="overview">Overview</h2>
      <p>
        NIS2 Article 11 requires Member States to designate CSIRTs with documented incident
        handling, advisory dissemination, and cross-border cooperation. OpenCSIRT is the working
        surface for those three jobs. It does not replace IRFlow's per-incident workflow engine
        and it is not a SIEM — it is the layer that turns IRFlow incidents and ThreatFlow IOCs
        into advisories, NIS2 Article 23 notifications, and peer-shareable records.
      </p>
      <p>
        The four core jobs the platform handles:
      </p>
      <ul>
        <li>
          <strong>Constituency tracking</strong> — a directory of organisations served, with
          sector, NIS2 status, and contact-of-record.
        </li>
        <li>
          <strong>Incident coordination</strong> — abuse-mailbox triage, IRFlow handoffs, and
          peer-CSIRT escalations with CITADEL-attested timelines.
        </li>
        <li>
          <strong>Advisory authoring</strong> — CSAF 2.0 documents generated by the Python
          advisory subsystem, reviewed by <code>csirt_lead</code>, and published with TLP
          enforcement to constituents and federated peers.
        </li>
        <li>
          <strong>Federated trust</strong> — peer CSIRTs exchange advisories and IOC bundles
          over a JWT-gated handshake protocol; no shared MISP infrastructure required.
        </li>
      </ul>

      <h2 id="key-features">Key features</h2>
      <ul>
        <li>
          <strong>CSAF 2.0 advisory generation</strong> — a dedicated Python subsystem
          renders and validates CSAF 2.0 JSON, runs IOC enrichment (VirusTotal, AlienVault OTX),
          and returns the sealed document to the Go API.
        </li>
        <li>
          <strong>TAXII 2.1 / STIX 2.1 compatible IOC ingest</strong> — ThreatFlow IOC bundles
          are pulled on a configurable schedule and attached to incidents.
        </li>
        <li>
          <strong>NIS2 Article 23 aggregate reporting</strong> — when an advisory is published
          for a NIS2-scoped constituency, a notification is automatically pushed to NIS2 Compass.
        </li>
        <li>
          <strong>Six-role RBAC</strong> — <code>viewer</code>, <code>external_peer</code>,{' '}
          <code>analyst</code>, <code>operator</code>, <code>csirt_lead</code>, <code>admin</code>.
          Publishing advisories and escalating to peers requires <code>csirt_lead</code> or
          higher.
        </li>
        <li>
          <strong>CITADEL-attested evidence</strong> — every incident open, close, advisory
          publish, and peer escalation is emitted as a signed event into the CITADEL WORM chain
          via a transactional outbox.
        </li>
        <li>
          <strong>Peer-CSIRT handshake protocol</strong> — JWT-gated federation: peers read
          advisories at their TLP tier and push back IOC bundles without requiring MISP.
        </li>
        <li>
          <strong>sinauth SSO</strong> — dashboard login uses OAuth 2.0 / OIDC (authorization
          code + PKCE S256) delegated to <a href="/docs/identity">sinauth</a>; the API validates RS256 tokens against the
          sinauth JWKS endpoint.
        </li>
      </ul>

      <h2 id="architecture">Architecture</h2>
      <p>
        OpenCSIRT is composed of four processes: a stateless Go API (HTTP, chi router), a
        Python CSAF advisory subsystem, a React + Vite operator dashboard, and PostgreSQL 16.
        The Go API owns all business logic, mints JWTs, enforces RBAC, and runs an in-process
        CITADEL outbox watcher goroutine that drains queued evidence events on a configurable
        tick.
      </p>
      <p>
        The Python advisory subsystem binds only on loopback (<code>127.0.0.1:8089</code>)
        and is called exclusively by the Go API using a service JWT. It is intentionally
        separated so that CSAF tooling, IOC enrichment connectors (VirusTotal, OTX, URLhaus),
        and YARA bindings live in the Python ecosystem without being embedded in the Go binary.
      </p>
      <p>
        Every CITADEL event is written into <code>citadel_outbox</code> inside the same database
        transaction that writes the business row, guaranteeing that outbox rows and business
        state are always consistent on commit. The watcher retries failed emissions until the
        retry budget is exhausted, at which point the row is marked <code>failed</code> and
        recorded in the audit log.
      </p>

      <div className="callout-note">
        <strong>Why two languages?</strong> Go handles the stateless API, HMAC signing,
        JWT management, and the outbox watcher. Python hosts the CSAF toolchain
        (<code>csaf-tools</code>), IOC enrichment SDKs, YARA bindings, and ML triage
        classifiers — all of which ship Python-first. The boundary is a loopback HTTP call,
        not a service mesh.
      </div>

      <h2 id="ports-endpoints">Ports &amp; endpoints</h2>

      <div className="docs-table-wrapper">
        <table className="docs-table">
          <thead>
            <tr>
              <th>Service</th>
              <th>Port</th>
              <th>Notes</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Go API</td>
              <td><code>8088</code></td>
              <td><code>OPENCSIRT_HTTP_ADDR</code></td>
            </tr>
            <tr>
              <td>Python advisory subsystem</td>
              <td><code>8089</code></td>
              <td><code>OPENCSIRT_ADVISORY_SERVICE_URL</code>; loopback only</td>
            </tr>
            <tr>
              <td>React dashboard</td>
              <td><code>3088</code></td>
              <td>nginx in production, Vite dev server locally</td>
            </tr>
            <tr>
              <td>PostgreSQL 16</td>
              <td><code>5432</code></td>
              <td>Cluster-internal</td>
            </tr>
          </tbody>
        </table>
      </div>

      <p>Key API endpoints (full contract in <code>api/openapi.yaml</code>):</p>

      <div className="docs-table-wrapper">
        <table className="docs-table">
          <thead>
            <tr>
              <th>Method</th>
              <th>Path</th>
              <th>Purpose</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><code>GET</code></td>
              <td><code>/api/v1/health</code></td>
              <td>Liveness — returns <code>db</code>, <code>advisory_service</code>, and <code>uptime_seconds</code></td>
            </tr>
            <tr>
              <td><code>POST</code></td>
              <td><code>/api/v1/auth/login</code></td>
              <td>JWT issuance</td>
            </tr>
            <tr>
              <td><code>GET</code> <code>POST</code></td>
              <td><code>/api/v1/constituencies</code></td>
              <td>Constituency directory CRUD</td>
            </tr>
            <tr>
              <td><code>GET</code> <code>POST</code></td>
              <td><code>/api/v1/incidents</code></td>
              <td>Triage queue and incident creation</td>
            </tr>
            <tr>
              <td><code>POST</code></td>
              <td><code>/api/v1/incidents/{'{id}'}/close</code></td>
              <td>Close incident and emit CITADEL event</td>
            </tr>
            <tr>
              <td><code>GET</code> <code>POST</code></td>
              <td><code>/api/v1/advisories</code></td>
              <td>Draft and list CSAF 2.0 advisories</td>
            </tr>
            <tr>
              <td><code>POST</code></td>
              <td><code>/api/v1/advisories/{'{id}'}/publish</code></td>
              <td>Publish, enforce TLP, fan out to peers</td>
            </tr>
            <tr>
              <td><code>POST</code></td>
              <td><code>/api/v1/integrations/irflow/incident</code></td>
              <td>HMAC-signed IRFlow inbound webhook</td>
            </tr>
            <tr>
              <td><code>GET</code></td>
              <td><code>/api/v1/metrics/snapshot</code></td>
              <td>JSON dashboard snapshot</td>
            </tr>
          </tbody>
        </table>
      </div>

      <h2 id="integration">Integration</h2>
      <p>
        OpenCSIRT integrates with four other opensecstack platforms. All cross-platform calls
        use HMAC-SHA256 signed envelopes with a replay window enforced by CITADEL.
      </p>

      <div className="docs-table-wrapper">
        <table className="docs-table">
          <thead>
            <tr>
              <th>Platform</th>
              <th>Direction</th>
              <th>Purpose</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><a href="/docs/platforms/threatflow"><strong>ThreatFlow</strong></a></td>
              <td>Pull (60 s default)</td>
              <td>IOC bundles attached to incidents; CSAF advisories pushed on publish</td>
            </tr>
            <tr>
              <td><a href="/docs/platforms/irflow"><strong>IRFlow</strong></a></td>
              <td>Inbound webhook</td>
              <td>HMAC-SHA256 verified — IRFlow incidents become OpenCSIRT incidents</td>
            </tr>
            <tr>
              <td><a href="/docs/platforms/nis2compass"><strong>NIS2 Compass</strong></a></td>
              <td>Push on publish</td>
              <td>Article 23 notification when a NIS2-scoped advisory is published</td>
            </tr>
            <tr>
              <td><a href="/docs/platforms/vertguard"><strong>VertGuard</strong></a></td>
              <td>Subscriber</td>
              <td>CVE advisories pulled from VertGuard, embedded into outbound CSAF</td>
            </tr>
            <tr>
              <td><strong>CITADEL</strong></td>
              <td>Outbox push</td>
              <td><code>opencsirt.incident_opened/closed</code>, <code>advisory_published</code>, <code>escalation_sent</code></td>
            </tr>
          </tbody>
        </table>
      </div>

      <p>Minimum required environment variables to bring up OpenCSIRT:</p>

      <CodeBlock
        language="bash"
        filename=".env"
        code={`OPENCSIRT_DB_URL=postgres://opencsirt:opencsirt@postgres:5432/opencsirt
OPENCSIRT_JWT_SECRET=<32+ random bytes>
OPENCSIRT_PASSWORD_PEPPER=<32+ random bytes>
OPENCSIRT_USERS=operator:operator:<sha256hex>
OPENCSIRT_ADVISORY_SERVICE_URL=http://advisory:8089
OPENCSIRT_CITADEL_API_URL=https://citadel.internal
OPENCSIRT_CITADEL_HMAC_SECRETS=<hmac>
OPENCSIRT_THREATFLOW_API_URL=https://threatflow.internal
OPENCSIRT_IRFLOW_WEBHOOK_SECRET=<hmac>`}
      />

      <p>
        To run locally in development mode (no CITADEL or ThreatFlow required), copy{' '}
        <code>.env.example</code> as-is — it ships with <code>OPENCSIRT_DEV_MODE=true</code>{' '}
        and a dry-run CITADEL outbox:
      </p>

      <CodeBlock
        language="bash"
        code={`git clone https://github.com/opensecstack/opensecstack
cd opensecstack/opencsirt
cp .env.example .env
make dev
# API: http://localhost:8088
# Dashboard: http://localhost:3088  (login: operator / operator)`}
      />

      <h2 id="full-documentation">Full documentation</h2>
      <p>
        The complete OpenCSIRT documentation — configuration reference, operator handbook,
        peer handshake protocol, CSAF advisory authoring guide, and integration guides — is
        available in the repository:
      </p>
      <p>
        <a
          href="https://github.com/opensecstack/opensecstack/tree/main/opencsirt/docs"
          target="_blank"
          rel="noopener noreferrer"
        >
          github.com/opensecstack/opensecstack/tree/main/opencsirt/docs
        </a>
      </p>
    </DocsLayout>
  )
}
