apiVersion: v1
kind: Secret
metadata:
  name: {{ include "community.fullname" . }}-secrets
type: Opaque
stringData:
  dbUrl: {{ .Values.secrets.dbUrl | quote }}
  jwtSecret: {{ .Values.secrets.jwtSecret | quote }}
  passwordPepper: {{ .Values.secrets.passwordPepper | quote }}
  users: {{ .Values.secrets.users | quote }}
  citadelHmacSecrets: {{ .Values.secrets.citadelHmacSecrets | quote }}
  citadelApiUrl: {{ .Values.secrets.citadelApiUrl | quote }}
