apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opensecstack.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
    {{- include "opensecstack.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size | quote }}
  {{- if .Values.postgres.persistence.storageClass }}
  storageClassName: {{ .Values.postgres.persistence.storageClass | quote }}
  {{- end }}
