apiVersion: v1
kind: Service
metadata:
  name: {{ include "opensecstack.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
    {{- include "opensecstack.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
