{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vertguard-ml.fullname" . }}-secrets
  labels:
    {{- include "vertguard-ml.labels" . | nindent 4 }}
type: Opaque
data:
  registry-access-key: {{ default "" .Values.secret.registryAccessKey | b64enc | quote }}
  registry-secret-key: {{ default "" .Values.secret.registrySecretKey | b64enc | quote }}
{{- end }}
